name: CI/CD Docker Hub to Swarm Imediato

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USER: lucasgfeldmann
  IMAGE_NAME: trabalho-cn-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest

  deploy-to-swarm:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Liberar espaço
        run: |
          docker system prune -f
          find $HOME/actions-runner/_diag -name "*.log" -mtime +3 -delete 2>/dev/null || true

      - name: Atualizar o Docker Swarm via Stack
        run: |
          docker stack deploy -c docker-compose.yml minha_stack_app --with-registry-auth